### ISSUE TITLE
When do you plan to release the training code

### ISSUE THREAD

**Issue by syfbme** [Time-Travel-Rephotography/Time-Travel-Rephotography.github.io#2]

**Comment by SarkarKurdish** [comment]
i've been waiting for 3 month too, i hope to get a date

**Comment by digitalblossom** [comment]
Still no updates apparently. The "coming soon" was removed from the website a few months ago

**Comment by RajvirSingh1313** [comment]
When will code will be released? I have some family photos, They have some white scratches on them. If you guys know any other program to fix that problem then that would be great for me.

**Comment by digitalblossom** [comment]
> When will code will be released? I have some family photos, They have some white scratches on them. If you guys know any other program to fix that problem then that would be great for me.

you could post it on reddit.com/r/estoration

**Comment by RajvirSingh1313** [comment]
> > When will code will be released? I have some family photos, They have some white scratches on them. If you guys know any other program to fix that problem then that would be great for me.
> 
> you could post it on reddit.com/r/estoration

Sorry for the late reply, I saw your message pretty earlier but forgot to reply but anyways I will surely check it. Thanks for the help

**Comment by cmdlinebeep** [comment]
Are you guys going to open source the actual project?

**Comment by RajvirSingh1313** [comment]
> Are you guys going to open source the actual project?

I don't think so as it is been like a lot of months since this issue opened, maintainers didn't even comment once. So I think they just left it

**Comment by roxanneluo** [comment]
The code is now released! We've also included Colab demos to enable users to easily try out our method. Don't hesitate to play with it if you've got some old photos you're eager to try out!

**Comment by RajvirSingh1313** [comment]
@roxanneluo Thanks Alot
