### ISSUE TITLE
Colab execution issue

### ISSUE THREAD

**Issue by ionultd** [Time-Travel-Rephotography/Time-Travel-Rephotography.github.io#3]
Thanks' very much for this code release.

I get these errors running the Colab notebook at the end.

`FileNotFoundError                         Traceback (most recent call last)
<ipython-input-22-199e9418d1e7> in <module>()
     19         results_dir="results/"
     20 ))
---> 21 main(args)

5 frames
/usr/local/lib/python3.7/dist-packages/torch/serialization.py in __init__(self, name, mode)
    209 class _open_file(_opener):
    210     def __init__(self, name, mode):
--> 211         super(_open_file, self).__init__(open(name, mode))
    212 
    213     def __exit__(self, *args):

FileNotFoundError: [Errno 2] No such file or directory: 'checkpoint/encoder/checkpoint_b.pt'`

**Comment by roxanneluo** [comment]
Did you download the models by running the `./scripts/download_checkpoints.sh`?

**Comment by m3l7** [comment]
@roxanneluo it appears that the files on drive are too big so the script fail to download the files (when dowloading the files manually, google drive opens a form to confirm that you want to download a big file). I'm trying to find a solution

**Comment by roxanneluo** [comment]
Yea, it seems to be related to the files being large and downloaded too many times. You can confirm that you'd like to download the big file. 
Maybe you can try copying to your own google drive and replace the `gdown` commands with ids from your own drive
```
gdown --id <id_on_your_own_drive_to_the_copied_file> -O <output_path>
```

Related resources: https://stackoverflow.com/questions/48735600/file-download-from-google-drive-to-colaboratory

**Comment by roxanneluo** [comment]
I've copied the weights to a shared drive to bypass the quota issue for downloading big files from gdrive. Try using the code below to download the weights instead. Does it work for you?

```
set -exo

mkdir -p checkpoint
gdown https://drive.google.com/uc?id=1YLB-3ZCv6FRAWwCHkTvUou_CAvDcb5Pr -O checkpoint/e4e_ffhq_encode.pt
gdown https://drive.google.com/uc?id=1aSnTVHGNzQ-Eh5rNDOrOc_4SjQbNMq3B -O checkpoint/stylegan2-ffhq-config-f.pt
gdown https://drive.google.com/uc?id=12BHlsSQM0D8KyXprIc7WmJRLWBWdtF56 -O checkpoint/vgg_face_dag.pt
mkdir -p checkpoint/encoder
gdown https://drive.google.com/uc?id=1fXBCyBKNEZfeiI6LEHTEnUg_DjWHJy5r -O checkpoint/encoder/checkpoint_b.pt
gdown https://drive.google.com/uc?id=1YnQEPf7FyfZxAVQg-CpbvdF4otZeTOZh -O checkpoint/encoder/checkpoint_g.pt
gdown https://drive.google.com/uc?id=1kelQK3pUdeHwu8uVE7A4WZH_EjHxGE6v -O checkpoint/encoder/checkpoint_gb.pt

pushd third_party/face_parsing
  mkdir -p res/cp
  gdown https://drive.google.com/uc?id=1vwm4BcAKISQgcJLvTUcvesk73UIYdDMF -O res/cp/79999_iter.pth
popd
```

**Comment by ionultd** [comment]
Has the colab been updated with your changes?

**Comment by m3l7** [comment]
I confirm the new code is working

**Comment by roxanneluo** [comment]
Great!
