### ISSUE TITLE
Colab Assertion Failed Issue

### ISSUE THREAD

**Issue by malewpro** [Time-Travel-Rephotography/Time-Travel-Rephotography.github.io#4]
I've created my own copy of the colab project and have managed to successfully implement it up until the final stage. I get this error when running the program using the sample image of Lincoln:

`/usr/local/lib/python3.7/dist-packages/torch/nn/functional.py:3635: UserWarning: Default upsampling behavior when mode=bilinear is changed to align_corners=False since 0.4.0. Please specify align_corners=True if the old behavior is desired. See the documentation of nn.Upsample for details.
  "See the documentation of nn.Upsample for details.".format(mode)

python test.py /content/Time-Travel-Rephotography/results/Abraham Lincoln_01/input_sibling /content/Time-Travel-Rephotography/results/Abraham Lincoln_01/skin_mask/face_parsing

0it [00:00, ?it/s]

---------------------------------------------------------------------------

error                                     Traceback (most recent call last)

<ipython-input-15-199e9418d1e7> in <module>()
     19         results_dir="results/"
     20 ))
---> 21 main(args)

2 frames

/content/Time-Travel-Rephotography/tools/match_histogram.py in main(args)
    144 
    145     mask_A = cv2.resize(cv2.imread(args.ref_mask, 0), A.shape[:2][::-1],
--> 146                         interpolation=cv2.INTER_NEAREST) > 0 if args.ref_mask else None
    147     mask_B = cv2.resize(cv2.imread(args.src_mask, 0), B.shape[:2][::-1],
    148                         interpolation=cv2.INTER_NEAREST) > 0 if args.src_mask else None

error: OpenCV(4.1.2) /io/opencv/modules/imgproc/src/resize.cpp:3720: error: (-215:Assertion failed) !ssize.empty() in function 'resize''

**Comment by roxanneluo** [comment]
Looks like tools/parse_face wasn’t executed properly and mask was not generated.

Were the checkpoints downloaded properly? Check third_party/face_parsing/res/cp

**Comment by malewpro** [comment]
The solution to #3 fixed it! You're right that the checkpoints weren't properly downloaded. Code is working now!
