### ISSUE TITLE
Black Image Output

### ISSUE THREAD

**Issue by blessedcoolant** [Time-Travel-Rephotography/Time-Travel-Rephotography.github.io#7]
The colab works perfectly fine but when I try to run the code locally, the final result is always a black image.

Everything seems to be working as intended. The face, contextual, noise and etc all show up correctly and begin to process. You can even visualize this data on tensorboard. However after a few steps -- it's random.. sometime 10 steps sometimes 20 steps .. all the data gets changed to "**nan**" and as a result the output goes black.

Not sure what is going wrong. Any help? Happens the same with any image and any model/checkpoint. Any help would be greatly appreciated. @roxanneluo

**Comment by blessedcoolant** [comment]
Any help? I noticed a pattern. The whole thing goes "nan" after the 10th iteration. There are loss values until then. And it's always the 10th iteration. I've changed and lowered all values to see if anything helps. Nothing does.

Any help understanding this issue would be greatly appreciated. @roxanneluo

**Comment by ialhashim** [comment]
Nans seem to happen a lot of times, but I tried running it again and it worked somehow.

**Comment by roxanneluo** [comment]
It could be because of high color transfer loss weights. Could you try lowering it and testing again?

**Comment by roxanneluo** [comment]
Can you share the input image for me to test on it to reproduce the problem?

**Comment by ialhashim** [comment]
@roxanneluo for my case the problem actually appears in the provided Lincon sample. Without changing anything or giving it any  new image or parameter. It feels like an nondeterministic behavior. 

Further more, dependency on older CUDA/PyTorch is a headache to get it to compile the first time (StyleGAN fault).

**Comment by blessedcoolant** [comment]
Yep. I get the error even on the Lincoln image that ships with this repo. No changes made to the basic inference command provided on the repo page.

**Comment by ialhashim** [comment]
Skipping NaN causing losses (I suspect its the contextual loss) enables the optimization to progress (i.e. just adding a nan check in the joint_loss.py)

![image](https://user-images.githubusercontent.com/2434978/155834191-75417858-7a88-4ad5-bd2d-c0b785763ac8.png)

**Comment by Kazakov-Alexandr** [comment]
Hello! I have found that if I exclude the "relu1_2" option from the "--cx_layers" list, then the NaN error does not appear.
